### PR TITLE
@graphql-ez/plugin-nexus

### PR DESCRIPTION
**Pull request by PabloSzx**
Official plugin for https://nexusjs.org/

### CODE REVIEW

**Comment by benbender** [comment]
Just out of curiosity: What is the benefit of having a distinct `nexus-plugin` instead of simply generating the schema and using `plugin-schema`?

Background: I'm using https://giraphql.com/ in combination with `graphql-ez` in one of my client-projects. `GiraphQL` is very similar to `nexus` in scope, but, imho, more generic and mature. Up until this point I didn't saw any benefit in a more tight integration via an own plugin. Have I missed smth?

**Comment by PabloSzx** [comment]
Hi, this plugin is not completely needed at all, this is just a convenience package, which also adds support for using for example, the plugin of scalars with nexus, and very useful in my opinion, for not needing to do manually creating the schema by manually importing every type, add it to "types" property of the "makeSchema", and just simply do "ezApp.registerNexus.objectType" and then importing the file before calling the "buildApp" or simply adding a dynamic import on the "prepare" property in either "buildApp" or in the "CreateApp"

**Comment by PabloSzx** [comment]
About GiraphQL I'm completely aware of its existence, just I haven't used it personally, but maybe a convenience plugin just like this one could be useful for GiraphQL as well

**Comment by benbender** [comment]
(extracted the discussion about a possible giraphql-plugin into issue #324)

**Comment by PabloSzx** [comment]
After thinking more about this plugin, maybe it's not worth it for this specific plugin to exist and just let it be its own thing and just specify the already built schema, same thing for the giraphql plugin #324, maybe I'm wrong, but it would only be useful for integration with the scalars and graphql-upload plugins, for nexus (and also type-graphql) in specific the cumbersome of building the schema is the inconvenience I was aiming to fix hooking them into the same ez app building process, what do you think @benbender

**Comment by nghiepit** [comment]
I'm planning to convert to `graphql-ez` from 'mercurius', so should I wait for this PR merge?

**Comment by PabloSzx** [comment]
> I'm planning to convert to `graphql-ez` from 'mercurius', so should I wait for this PR merge?

As I mentioned before, this plugin is just a convenience plugin, it's not required at all, you can use the "schema" configuration inside the "CreateApp", here is a small example with nexus without this possible plugin https://github.com/PabloSzx/graphql-ez/tree/main/examples/fastify/nexus

**Comment by PabloSzx** [comment]
I have decided that this plugin is not the best, having in mind separation of concerns and maintainability, this plugin was only created for convenience but maybe it's not worth the pros and cons

**Pull request closed without merging**
