### PR TITLE
sveltekit support

### LINKED ISSUE #146: [feat-request] Support Sveltekit?
I was poking around with [sveltekit](https://kit.svelte.dev/) lateley and liked it very much. So I was asking myself if there are any plans to support it in graphql-ez? 

The interesting/complicated part of this effort would be that sveltekit does much of the work as a vite-compiler-plugin beforehand and therefor the exposed request/response-objects are quite limited (at least atm) and a bit unusual...

### PR DESCRIPTION
**Pull request by PabloSzx**
closes #146 

@benbender if you want to collaborate on this you are more than welcome 👍

### CODE REVIEW

**Comment by PabloSzx** [comment]
@benbender Here is the first working version https://github.com/PabloSzx/graphql-ez/blob/sveltekit/examples/sveltekit/src/routes/graphql.ts if you want please take a look and test it and give opinions or suggestions https://github.com/PabloSzx/graphql-ez/blob/sveltekit/packages/sveltekit/main/src/index.ts

What I did to reduce the friction with the current node.js integrations is to create a fake IncomingMessage that only has access to "headers" and "method", which is what most of the integrations or envelop plugins use anyways

**Comment by benbender** [comment]
Hey! Thanks for the effort! I would love to play with it and so I'll just added an additional route with the newly created `graphq-ez`-handler into my play-project and it seems to work fine initially with a mildly complex schema generated by `giraphql`. Great job!

Problem atm seems to be that the `sveltekit`-integration isn't known to the core yet and therefor I can't test any plugins without patching the `sveltekit`-integration into the compatibility-list. Is there some kind of undocumented switch to turn off the compatibility check or something? And if not, might it be worth adding one for development?

**Comment by PabloSzx** [comment]
> Hey! Thanks for the effort! I would love to play with it and so I'll just added an additional route with the newly created `graphq-ez`-handler into my play-project and it seems to work fine initially with a mildly complex schema generated by `giraphql`. Great job!
> 
> Problem atm seems to be that the `sveltekit`-integration isn't known to the core yet and therefor I can't test any plugins without patching the `sveltekit`-integration into the compatibility-list. Is there some kind of undocumented switch to turn off the compatibility check or something? And if not, might it be worth adding one for development?

the compatibility list doesn't make sense to turn off for the specific plugins that requires it because the "onIntegrationRegister" lifecycle has to be hardcoded for the integration that it supports 😞

**Comment by PabloSzx** [comment]
for the IDE plugins like graphiql and altair or voyager, what the plugins will need to export is an extra handler that adds support for sveltekit, it's not hard, but the altair required a dynamic route

for the plugins: 
- upload
- websockets
- new sse

they are virtually impossible to add support for sveltekit 😞

**Comment by benbender** [comment]
What I had in mind was a simple option, probably undocumented, which just circumvents the checks entirely. Not meant to be used regularly, but just for development of new plugins/integrations. 

So for example one could have something like:
```ts
    ezApp = createEZAppFactory(
      {
        integrationName: "sveltekit",
        disableCompatibilityChecks: true
      },
      appConfig
    );
```

And a check for it here:
https://github.com/PabloSzx/graphql-ez/blob/987869848be915aa05fa41deec7cf0858b6518f1/packages/core/main/src/app.ts#L60

**Comment by PabloSzx** [comment]
> What I had in mind was a simple option, probably undocumented, which just circumvents the checks entirely. Not meant to be used regularly, but just for development of new plugins/integrations.
> 
> So for example one could have something like:
> 
> ```ts
>     ezApp = createEZAppFactory(
>       {
>         integrationName: "sveltekit",
>         disableCompatibilityChecks: true
>       },
>       appConfig
>     );
> ```
> 
> And a check for it here:
> https://github.com/PabloSzx/graphql-ez/blob/987869848be915aa05fa41deec7cf0858b6518f1/packages/core/main/src/app.ts#L60

the compatibility list is only there for the lifecycle "onIntegrationRegister", the plugins that don't use that lifecycle, don't specify it, there isn't any purpose behind disabling them, and if you are creating new plugins, you can simply don't specify the compatibilityList field / not use onIntegrationRegister / add the integration you are working on to the list

**Comment by benbender** [comment]
Thanks for the invite! I'll have a look onto altair/graphiql later today or tomorrow as I have some things to check on my todo-list beforehand...

There are also some slight issues with the typings of the new sveltekit-integration as, f.e., I'm using a global type for `Locals` which isn't correctly picked up by the Request/ServerRequest-type. I just noticed this while setting up my context...

For everything related to upload/multipart/streams in sveltekit, there might be some hope for the future as the [Whatwg Streams-API](https://streams.spec.whatwg.org/) gets more support (deno, node16, ...) and there are some quite active discussions about it at sveltejs/kit#1563, sveltejs/kit#2212 etc and there might also be a chance for some sort of support for [connect-handlers](https://github.com/sveltejs/kit/issues/1563#issuecomment-900304554) before 1.0.

**Comment by benbender** [comment]
I've added the most primitive support for graphiql [here](https://github.com/benbender/graphql-ez/commit/02f44da59daefabafbd64c942756291103d5f2df).

Before going further, I wanted to ask, if there is any specific reason why you've split the routes for the nextjs-handler between graphql and graphiql?

The straight-forward way to implement compatibility for `sveltekit`, in the same manner like you did for nextjs, seems to be to duplicate the `GraphiQLHandler`-method and adapt it for `sveltekit`.

That approach seems repetitive to me and I would have opted for another approach to handle the split between the `graphiql`/`graphql`-handlers directly inside the `graphql-ez`-app - much like `graphql-helix` did with its `shouldRenderGraphiQL()`-method. Following that approach would enable the nextjs/sveltekit-integrations also to be simply added via the plugin-interface without having the need to add another route-handler...

**Comment by PabloSzx** [comment]
> Before going further, I wanted to ask, if there is any specific reason why you've split the routes for the nextjs-handler between graphql and graphiql?

I don't think there is a specific reason for it, it was just more of an opinionated decision, I felt like going to graphiql should be a different path and 100% conscious decision, just like going to altair is, but I understand 100% that having it in the same path with logic like "if (shouldRenderGraphiQL(" is something a lot of people expect, I will work on it 👍 it _might_ mean some changes for some integrations

**Comment by PabloSzx** [comment]
> > Before going further, I wanted to ask, if there is any specific reason why you've split the routes for the nextjs-handler between graphql and graphiql?
> 
> I don't think there is a specific reason for it, it was just more of an opinionated decision, I felt like going to graphiql should be a different path and 100% conscious decision, just like going to altair is, but I understand 100% that having it in the same path with logic like "if (shouldRenderGraphiQL(" is something a lot of people expect, I will work on it 👍 it _might_ mean some changes for some integrations

https://github.com/PabloSzx/graphql-ez/pull/236 🎉 I want to update the graphiql instance to have the changes of https://github.com/contrawork/graphql-helix/pull/44 & https://github.com/contrawork/graphql-helix/pull/37 before merging tho 👌

**Comment by PabloSzx** [comment]
> There are also some slight issues with the typings of the new sveltekit-integration as, f.e., I'm using a global type for `Locals` which isn't correctly picked up by the Request/ServerRequest-type. I just noticed this while setting up my context...

@benbender what do you think is the solution for that, you are using those custom types in the "buildContext"?

**Comment by benbender** [comment]
> @benbender what do you think is the solution for that, you are using those custom types in the "buildContext"?

I've would have used the same solution as you came up with.

Problem here is the young age of sveltekit and there is mix of code out there where `Local` is defined as a global ambient-type and there is roughly an equally amount of code which defines it as local type and needs to inject it. So for the moment you have to augment it manually... And that's also what sveltekit does in the RequestHandler-Type and similar. So you are good to go I would say!

**Comment by PabloSzx** [comment]
@benbender The only thing left is docs, I will work on them now

**Pull request merged**
